trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './MedicalApp.API.csproj'
    arguments: '--configuration Release'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    workingDir: MedicalApp-SPA

- task: Npm@1
  displayName: 'Build Angular'
  inputs:
    command: custom
    customCommand: run build
    workingDir: MedicalApp-SPA

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'MedicalApp-SPA/dist'